# Generated by Django 3.2.6 on 2021-08-14 00:15

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.set_user_image_name),
        ),
    ]
