# Generated by Django 3.2.6 on 2021-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='thumbnail_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
