# Generated by Django 3.2.6 on 2021-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='total_accumulated_fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
