# Generated by Django 3.2.6 on 2021-08-13 07:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_challenge_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='thumbnail_url',
            field=models.FileField(blank=True, null=True, upload_to=core.models.set_challenge_image_name),
        ),
        migrations.AlterField(
            model_name='verification',
            name='image_url',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=core.models.set_verification_image_name),
        ),
    ]
