# Generated by Django 3.2.6 on 2021-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_total_accumulated_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='total_accumulated_fine',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='file_url',
        ),
        migrations.AddField(
            model_name='challenge',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='participation',
            name='total_distribute_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='verification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
