# Generated by Django 3.2.6 on 2021-08-13 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_verification_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 19, 41, 14, 891348)),
        ),
    ]
